/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/produit/$slug': typeof ProduitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/catalogue'
    | '/contact'
    | '/produit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/catalogue'
    | '/contact'
    | '/produit/$slug'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/auth'
    | '/catalogue'
    | '/contact'
    | '/produit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
